spring:
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false
    atomikos:
      datasource:
        masterDataSource:
          unique-resource-name: account
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            driverClassName: com.mysql.jdbc.Driver
            username: pintuan
            url: jdbc:mysql://192.168.147.192:3306/pintuan?useSSL=false&useUnicode=true&characterEncoding=utf-8
            password: FJAOFbhS0sMzyZzY
        clusterDataSource:
          unique-resource-name: order
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            driverClassName: com.mysql.jdbc.Driver
            username: pintuan
            url: jdbc:mysql://192.168.147.192:3306/pintuan?useSSL=false&useUnicode=true&characterEncoding=utf-8
            password: FJAOFbhS0sMzyZzY

